---
driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local
      attrs_outputs:
        servers_virginia_private: private_ip_dc1
        servers_ohio_private: private_ip_dc2
        servers_virginia_public: public_dns_servers_virginia
        servers_ohio_public: public_dns_servers_ohio

platforms:
  - name: terraform

suites:
  - name: default
