---
driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local
      attrs_outputs:
        servers_gcp_private: private_ip_gcp
        servers_gcp_public: public_ip_gcp

platforms:
  - name: terraform

suites:
  - name: default
